# Import Statements

In [1]:
import numpy as np
import pandas as pd
import pickle
import gzip
from matplotlib import pyplot as plt
from tqdm import tqdm

# Read Files

In [2]:
df_train = pd.read_csv('Dataset/fmnist/fashion-mnist_train.csv')
df_test = pd.read_csv('Dataset/fmnist/fashion-mnist_test.csv')
classes = {0:"T-shirt/top",
1 :"Trouser",
2 :"Pullover",
3 :"Dress",
4 :"Coat",
5 :"Sandal",
6 :"Shirt",
7 :"Sneaker",
8 :"Bag",
9 :"Ankle boot"}

In [3]:
print(len(classes))

10


In [4]:
train_x = np.array(df_train.iloc[:,1:]).reshape(df_train.shape[0],784)
train_y = np.array(df_train.iloc[:,0])
test_x = np.array(df_test.iloc[:,1:]).reshape(df_test.shape[0],784)
test_y = np.array(df_test.iloc[:,0])

In [5]:
print(train_x.shape, train_y.shape)
print(test_x.shape, test_y.shape)

(60000, 784) (60000,)
(10000, 784) (10000,)


# Feed Forward Neural Network

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Activation
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.initializers import RandomNormal
from keras.models import load_model

In [7]:
# Preprocessing
train_x = (train_x.astype('float32')/255) - 0.5
test_x = (test_x.astype('float32')/255) - 0.5

train_y = to_categorical(train_y)
numerical_test_y = test_y
test_y = to_categorical(test_y)

print(train_x.shape, train_y.shape)
print(test_x.shape, test_y.shape)

(60000, 784) (60000, 10)
(10000, 784) (10000, 10)


In [8]:
# # Building the model
# model = Sequential([
#     Dense(128, activation='relu', input_shape=(784,), kernel_initializer=RandomNormal(mean=0.0, stddev=0.05, seed=0)),
#     Dense(64, activation='relu', kernel_initializer=RandomNormal(mean=0.0, stddev=0.05, seed=0)),
#     Dense(10, activation='softmax', kernel_initializer=RandomNormal(mean=0.0, stddev=0.05, seed=0)),
# ])

In [9]:
# # Compiling the model
# model.compile(
#   optimizer=SGD(learning_rate=0.1),
#   loss='categorical_crossentropy',
#   metrics=['accuracy'],
# )

In [10]:
# model.summary()

In [11]:
# # Train the model
# history = model.fit(
#   train_x,
#   train_y,
#   epochs=20,
#   batch_size=32,
# )

In [12]:
# plt.plot(history.history['loss'])
# plt.title('Training Loss Graph')
# plt.ylabel('loss')
# plt.xlabel('epoch')
# plt.legend(['train'], loc='upper right')
# plt.show()

In [13]:
# model.save('Q2_model.h5')

# Load Model

In [14]:
model = load_model('Q2_model.h5')

# Train Loss Graph

In [15]:
# Displayed in report

# Testing

In [16]:
# Overall Accuracy
model.evaluate(
  test_x,
  test_y
)

313/313 [==============================] - 1s 1ms/step - loss: 0.3024 - accuracy: 0.8961


[0.30240413546562195, 0.8960999846458435]

In [17]:
# Class-wise accuracy
predictions_ohe = model.predict(test_x)
predictions = np.argmax(predictions_ohe, axis=1)

In [18]:
my_confusion_matrix = np.zeros((len(classes),len(classes)), dtype=np.int64)

In [19]:
for i in range(test_x.shape[0]):
    my_confusion_matrix[numerical_test_y[i]][predictions[i]] += 1

In [20]:
print(my_confusion_matrix)

[[860   2  16  15   2   1  95   0   9   0]
 [  1 988   1   9   0   0   1   0   0   0]
 [ 15   0 815  11  81   1  74   0   3   0]
 [ 22  19  11 875  53   0  19   0   1   0]
 [  0   2  62  13 872   0  49   0   2   0]
 [  1   0   0   2   0 954   1  27   2  13]
 [127   1  58  19  62   0 723   0  10   0]
 [  0   0   0   0   0  14   0 927   0  59]
 [  2   1   4   1   2   1  13   1 975   0]
 [  0   0   1   0   0   6   0  21   0 972]]


In [21]:
class_wise_accuracies = np.zeros((len(classes)))
for i in range(len(classes)):
    class_wise_accuracies[i] = my_confusion_matrix[i][i]/np.sum(my_confusion_matrix[i])
    print('Accuracy of class {}: {}%'.format(i, class_wise_accuracies[i]*100))

print('\nOverall accuracy: {}%'.format(100*np.trace(my_confusion_matrix)/np.sum(my_confusion_matrix, axis=None)))

Accuracy of class 0: 86.0%
Accuracy of class 1: 98.8%
Accuracy of class 2: 81.5%
Accuracy of class 3: 87.5%
Accuracy of class 4: 87.2%
Accuracy of class 5: 95.39999999999999%
Accuracy of class 6: 72.3%
Accuracy of class 7: 92.7%
Accuracy of class 8: 97.5%
Accuracy of class 9: 97.2%

Overall accuracy: 89.61%
